# Generated by Django 5.0.1 on 2024-01-25 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_packetattackdetails_delete_packetbaseinfor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketBaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('src_ip', models.CharField(max_length=100)),
                ('dst_ip', models.CharField(max_length=100)),
                ('src_port', models.IntegerField()),
                ('dst_port', models.IntegerField()),
                ('method', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=50)),
                ('hostname', models.CharField(max_length=100)),
                ('user_agent', models.CharField(max_length=100)),
                ('referer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PacketAttackDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.CharField(max_length=100)),
                ('feature', models.CharField(max_length=100)),
                ('threat', models.CharField(max_length=100)),
                ('base_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.packetbaseinfo')),
            ],
        ),
    ]
