# Generated by Django 5.0.1 on 2024-01-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PacketAttackDetails',
        ),
        migrations.DeleteModel(
            name='PacketBaseInfo',
        ),
    ]
