# Generated by Django 5.0.1 on 2024-01-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_packetbaseinfo_referer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetbaseinfo',
            name='dst_port',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='packetbaseinfo',
            name='src_port',
            field=models.CharField(max_length=100),
        ),
    ]
