# Generated by Django 5.0.1 on 2024-01-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_packetbaseinfo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetbaseinfo',
            name='user_agent',
            field=models.TextField(),
        ),
    ]
