# Generated by Django 5.0.1 on 2024-01-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_packetbaseinfo_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetattackdetails',
            name='feature',
            field=models.TextField(),
        ),
    ]
